import type { Metadata } from "next"
import { siteMeta } from "@/lib/site-content"

export const sharedKeywords: string[] = [
  "PlasmIT",
  "PiMed",
  "QLMed",
  "Smart ICU on Mobile",
  "PiMed Life",
  "PiMed Elixir",
  "PiMed Nirvana",
  "ICU Monitoring Platform",
  "Smart ICU",
  "Mobile ICU Dashboard",
  "Integrated Care Dashboard",
  "AI Enabled Edge Device",
  "Medical IoT",
  "MIoT",
  "Real-time Data Streaming",
  "Anomaly Detection",
  "Intelligent Alerts",
  "Gen AI Clinical Pathways",
  "AI Driven Triage",
  "Predictive ICU Care",
  "AI ML Care Insights",
  "Digital Care Platform",
  "Care Delivery Platform",
  "Secure Data Store",
  "Fault Tolerant Platform",
  "FHIR",
  "Healthcare Interoperability",
  "Device Agnostic Platform",
  "Vendor Agnostic",
  "Edge Computing Healthcare",
  "24x7 Remote Intervention",
  "Continuous Monitoring",
  "Point-in-Time Care",
  "Clinical Pathway Automation",
  "Seamless Collaboration",
  "Care Workflow Digitisation",
  "Critical Care",
  "Intensive Care Unit",
  "ICU",
  "Semi ICU",
  "HDU",
  "CCU",
  "In-Patient Care",
  "Post-Discharge Care",
  "Emergency Care",
  "Tele-ICU Alternative",
  "Tele-Intensivist Alternative",
  "Connected Care",
  "Contextual Care",
  "Compliant Care",
  "Value-based Care",
  "Preventive Care",
  "Proactive Care",
  "Golden Hour",
  "Clinical Decision Support",
  "Actionable Care Insights",
  "Care Intervention",
  "Patient Deterioration Detection",
  "ICU Bed Utilisation",
  "Length of Stay Reduction",
  "Medical Error Reduction",
  "Mortality Reduction",
  "Care Provider Utilisation",
  "Cognitive Load Reduction",
  "Decentralised Care",
  "Future Ways of Care",
  "Health Technology",
  "Health-tech",
  "Digital Health",
  "Hospital",
  "Australia",
  "India",
  "Australia-headquartered",
  "India-first GTM",
  "Tier 1 Hospitals",
  "Tier 2 Hospitals",
  "Hospital SaaS",
  "Utilisation-based Pricing",
  "Per Bed Per Day",
  "Subscription Model",
  "Pilot-first Approach",
  "Start Small Scale Fast",
  "Convertible Notes",
  "Seed Stage",
  "Pre-Series A",
  "Healthcare Startup",
  "MOU",
  "Paid Pilot",
  "Government Health Traction",
  "Public Sector Healthcare",
  "ICU Market India",
  "Critical Care Market",
  "CAGR 8 Percent",
  "Multibillion Dollar Market",
  "Market Validation",
  "Provisional IP",
  "Patent Filed",
  "Healthcare Compliance",
  "India Regulatory Compliance",
  "Data Security Healthcare",
  "In-transit Security",
  "TRL 4",
  "Technology Readiness Level",
  "Product Advisory Council",
  "Save Lives",
  "Improve Efficiency",
  "Increase Brand Reputation",
  "Reduce ICU Cost",
  "Revenue Optimisation",
  "Hospital ROI",
  "5x ROI",
  "53000 Deaths Preventable",
  "5 Million Deaths India",
  "Litigation Cost Reduction",
  "Communication Inefficiency",
  "ICU Waste Reduction",
  "Resource Optimisation",
  "HAQ Index",
  "Healthcare Visionary",
  "Intensivist",
  "Cardiologist AI Lead",
  "Interoperability Lead",
  "Founding Team",
  "Australian Government Healthcare",
  "Indian Government Healthcare",
  "Narayana Health",
  "Ruban Hospitals",
  "Reddy Labs",
]

type PageMetadataInput = {
  title: string
  description: string
  path: string
  keywords?: string[]
}

export function buildPageMetadata({
  title,
  description,
  path,
  keywords,
}: PageMetadataInput): Metadata {
  const urlPath = path === "/" ? "/" : path.replace(/\/+$/, "")
  const fullTitle = `${title} | ${siteMeta.name}`
  const ogImageUrl = new URL("/media/og-image.png", siteMeta.url).toString()

  return {
    title,
    description,
    keywords: keywords ? [...sharedKeywords, ...keywords] : sharedKeywords,
    alternates: {
      canonical: urlPath,
    },
    openGraph: {
      title: fullTitle,
      description,
      url: urlPath,
      siteName: siteMeta.name,
      type: "website",
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: fullTitle,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [ogImageUrl],
    },
  }
}
